// Generated by IB v0.4.9 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <Accelerate/Accelerate.h>
#import <Accelerate/Accelerate.h>
#import <Foundation/Foundation.h>
#import <MessageUI/MessageUI.h>
#import <OpenGLES/OpenGLES.h>
#import <QuartzCore/QuartzCore.h>
#import <StoreKit/StoreKit.h>
#import <UIKit/UIKit.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface MainViewController: UIViewController

@property IBOutlet UIImageView * imageView;

-(IBAction) viewDidLoad;
-(IBAction) setImage:(id) sender;
-(IBAction) editImage:(id) sender;
-(IBAction) photoEditorCanceled:(id) editor;

@end

